In [1]:
# pip install torch==1.11

In [2]:
import torch
print(torch.__version__)

2.1.0+cu118


In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
# !nvidia-smi

### Introduction to tensors

## Creating tensors

In [5]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
# Get tensor back to python scalar
scalar.item()

7

In [8]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random tensors:

In [17]:
### Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0797, 0.2234, 0.8874, 0.2460],
        [0.4557, 0.3075, 0.0589, 0.1007],
        [0.9936, 0.0364, 0.6515, 0.9794]])

In [18]:
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [19]:
random_tensor = torch.rand(3,4)
zeros_tensor = torch.zeros(3,4)
zeros_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
ones_tensor = torch.ones(3,4)

In [21]:
### Create a range of tensors and tensors-like

In [22]:
one_to_ten = torch.arange(1,11)

In [23]:
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
# Creating tensors-like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [25]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [26]:
float_16_tensor = float_32_tensor.type(torch.float16)

### Manipulating tensors: Tensor operations

In [27]:
some_tensor = torch.rand([3,4])
some_tensor

tensor([[0.8721, 0.7114, 0.0964, 0.7808],
        [0.7368, 0.9237, 0.0698, 0.8436],
        [0.4083, 0.3258, 0.5940, 0.8934]])

In [28]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [29]:
tensor * 10, torch.mul(tensor, 10)

(tensor([10, 20, 30]), tensor([10, 20, 30]))

In [30]:
tensor * tensor

tensor([1, 4, 9])

In [31]:
torch.matmul(tensor, tensor)

tensor(14)

In [32]:
%%time
random_tensor.sum()

CPU times: user 186 µs, sys: 0 ns, total: 186 µs
Wall time: 160 µs


tensor(5.7707)

In [33]:
%%time
torch.sum(random_tensor)

CPU times: user 114 µs, sys: 19 µs, total: 133 µs
Wall time: 1.94 ms


tensor(5.7707)

### Tensor reshaping, squeezing, unsqueezing and stacking

In [34]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [35]:
# Reshape: Add extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [36]:
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [37]:
#Change the view (both share the same memory, el elemento z apunta al x, sim modificas z modificas x)
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [38]:
z[:,0] = 5.
x

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [39]:
# Stack tensors on top of each other, concatena
x_stacked = torch.stack([x,x])
x_stacked, x_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([2, 9]))

In [40]:
x_reshaped.shape, x_reshaped.squeeze().shape


(torch.Size([3, 3]), torch.Size([3, 3]))

### Interaction between Pytorch and Numpy

In [41]:
import torch
import numpy as np

In [42]:
array = np.arange(1.0, 10.0, 1.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

### Reproducibility (taking the random out of the random)

Random seed:

In [43]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
random_tensor_A, random_tensor_B

(tensor([[0.9660, 0.0050, 0.5171, 0.1970],
         [0.3815, 0.1488, 0.1984, 0.1060],
         [0.1992, 0.6283, 0.8600, 0.2059]]),
 tensor([[0.1731, 0.2842, 0.3109, 0.7578],
         [0.8902, 0.3383, 0.7498, 0.3476],
         [0.7857, 0.9668, 0.5042, 0.6469]]))

In [44]:
torch.manual_seed(123)
random_tensor_A = torch.rand(3,4)
torch.manual_seed(123)
random_tensor_B = torch.rand(3,4)
random_tensor_A, random_tensor_B

(tensor([[0.2961, 0.5166, 0.2517, 0.6886],
         [0.0740, 0.8665, 0.1366, 0.1025],
         [0.1841, 0.7264, 0.3153, 0.6871]]),
 tensor([[0.2961, 0.5166, 0.2517, 0.6886],
         [0.0740, 0.8665, 0.1366, 0.1025],
         [0.1841, 0.7264, 0.3153, 0.6871]]))

# Putting tensors and models on the GPU

In [45]:
tensor = torch.tensor([1,2,3], device="cpu")
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [46]:
# Move tensor to gpu if available
tensor_on_gpu = tensor.to("cuda")
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [47]:
# Move tensors back to cpu
tensor_on_cpu = tensor_on_gpu.to("cpu")
tensor_on_cpu, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [48]:
# Move tensors back to cpu
tensor_on_cpu = tensor_on_gpu.cpu()
tensor_on_cpu, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))